"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Choose the correct database file path
if 'PYTHONANYWHERE_DOMAIN' in os.environ:
    # Use the absolute path on the PythonAnywhere server
    DB_PATH = '/home/joshbelloUOL/COMP3011_WebServices_CW1/db.sqlite3'
else:
    # Use the dynamic path for Local Windows or the Examiner's PC
    DB_PATH = BASE_DIR / 'db.sqlite3'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

load_dotenv()
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-)%prnh47-z%u#$z00blir)+$*=6^be1=wifpa@+t08jd19la10'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['joshbellouol.eu.pythonanywhere.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api_app',
    'leaflet',
    'django_filters',
    'djangorestframework_mcp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.spatialite',
        'NAME': DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os, sys, glob

# Only configure GDAL/GEOS manually on Windows
if os.name == 'nt':
    import osgeo
    # Find the base directory of your Python environment (venv)
    venv_base = os.path.dirname(os.path.dirname(sys.executable))
    site_packages = os.path.join(venv_base, "Lib", "site-packages", "osgeo")

    if not os.path.exists(site_packages):
        venv_base = os.path.dirname(sys.executable)
        site_packages = os.path.join(venv_base, "Lib", "site-packages", "osgeo")

    # Set GDAL and GEOS Paths for Windows
    gdal_candidates = glob.glob(os.path.join(site_packages, "gdal*.dll"))
    if gdal_candidates:
        GDAL_LIBRARY_PATH = gdal_candidates[0]

    geos_candidates = glob.glob(os.path.join(site_packages, "geos_c.dll"))
    if geos_candidates:
        GEOS_LIBRARY_PATH = geos_candidates[0]

    # Windows SpatiaLite Path (Adjusted for your local machine)
    SPATIALITE_LIBRARY_PATH = r'C:\spatialite\mod_spatialite.dll'

    # Add folder to PATH so Windows finds dependencies
    spatialite_dir = os.path.dirname(SPATIALITE_LIBRARY_PATH)
    if os.path.exists(spatialite_dir) and spatialite_dir not in os.environ['PATH']:
        os.environ['PATH'] = spatialite_dir + ';' + os.environ['PATH']

    # PROJ LIB Config
    PROJ_LIB = os.path.join(os.path.dirname(osgeo.__file__), 'data', 'proj')
    os.environ['PROJ_LIB'] = PROJ_LIB

# 3. PYTHONANYWHERE CONFIG (Production Linux)
elif 'PYTHONANYWHERE_DOMAIN' in os.environ:
    # Use the pre-installed Linux SpatiaLite library
    SPATIALITE_LIBRARY_PATH = '/usr/lib/x86_64-linux-gnu/mod_spatialite.so'