# Generated by Django 5.2.11 on 2026-02-10 12:44

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elevation_gain', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0)),
                ('region', models.CharField(default=0.0, max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('popularity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('path', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api_app.trail')),
            ],
        ),
        migrations.CreateModel(
            name='TransportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUS', 'Bus Stop'), ('TRAIN', 'Train Station'), ('PARK', 'Car Park')], max_length=10)),
                ('station_name', models.CharField(max_length=100)),
                ('distance_from_trailhead_km', models.FloatField()),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_links', to='api_app.trail')),
            ],
        ),
    ]
