# Generated by Django 5.2.11 on 2026-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(default='Moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='trail',
            name='estimated_duration',
            field=models.CharField(default='0h', max_length=50),
        ),
    ]
