# Generated by Django 5.2.11 on 2026-02-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_transportlink_station_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportlink',
            name='distance_from_trailhead_km',
        ),
    ]
