# Generated by Django 5.2.11 on 2026-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_transportlink_distance_from_trailhead_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportlink',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
