# Generated by Django 5.2.11 on 2026-02-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_transportlink_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarParks',
            new_name='CarPark',
        ),
    ]
