# Generated by Django 5.2.11 on 2026-02-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_rename_carparks_carpark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Number of spaces', null=True),
        ),
    ]
