# Generated by Django 5.2.11 on 2026-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_carpark_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='has_disabled_parking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
