# Generated by Django 5.2.11 on 2026-02-16 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_alter_carpark_has_disabled_parking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailLogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hiked', models.DateField()),
                ('duration_minutes', models.IntegerField(help_text='Time taken in minutes')),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Cloudy', 'Cloudy'), ('Snow', 'Snow')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='How was this hike?')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
